services:
  - type: web
    name: image-processing-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn backend:app
    envVars:
      - key: FLASK_ENV
        value: production
